library(dplyr)
mechacar_mpg <- read.csv(file='MechaCar_mpg.csv',check.names=F,stringsAsFactors = F)
lm(qsec ~ hp, mechacar_mpg)
lm(vehicle_length ~ mpg, mechacar_mpg)
lm(vehicle_weight ~ mpg, mechacar_mpg)
lm(spoiler_angle ~ mpg, mechacar_mpg)
lm(ground_clearance ~ mpg, mechacar_mpg)
lm(AWD ~ mpg, mechacar_mpg)
lm(mpg ~ mpg, mechacar_mpg)
lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, data = mechacar_mpg)
summary(lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, data = mechacar_mpg))
